### IN THIS NOTEBOOK FEATURE ENGINEERNIGN HAS BEEN DONE (Combining features)

In [ ]:
import pandas as pd
df=pd.read_csv('feature_generated.csv')

In [13]:
pd.set_option('display.max_columns', None)
df.head(5)

,ID,ACCOUNT_TYPE,HIGH_CREDIT_OR_SANCTIONED_AMOUNT,MONTH_OPENED,CURRENT_BALANCE,ACTUAL_PAYMT_AMT,REPAYMENT_TENURE,AMOUNT_OVERDUE,PAYMENT_HISTORY_1,OWNERSHIP_TYPE,COLLATERALVALUE,TU_SCORE,MONTH_PAYMENT_HISTORY_START,MONTH_PAYMENT_HISTORY_END,MONTH_CERTIFIED,MONTH_LAST_PAYMENT,AGE,OCCUPATION_TYPE,GENDER,ACTUAL_ROI,COUNT_PAID,COUNT_LATE,COUNT_MORE_THAN_90,COUNT_0_TO_60,AVG_DAYS,COUNT_MISSING_DAYS,PERSONAL_LOANS,PROPERTY_LOANS,BUSINESS_LOANS,GOLD_LOANS,HOUSING_LOANS,KISAN_CREDIT_CARD_LOANS,EDUCATION_LOANS,CLOSED_PERSONAL_LOANS,CLOSED_PROPERTY_LOANS,CLOSED_BUSINESS_LOANS,CLOSED_GOLD_LOANS,CLOSED_HOUSING_LOANS,CLOSED_KISAN_CREDIT_CARD_LOANS,CLOSED_EDUCATION_LOANS,PROPERTY_LOANS_PAID_SUM,BUSINESS_LOANS_PAID_SUM,GOLD_LOANS_PAID_SUM,HOUSING_LOANS_PAID_SUM,PERSONAL_LOANS_PAID_SUM,KISAN_CREDIT_CARD_LOANS_PAID_SUM,EDUCATION_LOANS_PAID_SUM,PERSONAL_LOANS_SUM,PROPERTY_LOANS_SUM,BUSINESS_LOANS_SUM,GOLD_LOANS_SUM,HOUSING_LOANS_SUM,KISAN_CREDIT_CARD_LOANS_SUM,EDUCATION_LOANS_SUM,PERSONAL_LOANS_UNCLOSED_SUM,PROPERTY_LOANS_UNCLOSED_SUM,BUSINESS_LOANS_UNCLOSED_SUM,GOLD_LOANS_UNCLOSED_SUM,HOUSING_LOANS_UNCLOSED_SUM,KISAN_CREDIT_CARD_UNCLOSED_SUM,EDUCATION_LOANS_UNCLOSED_SUM,ALL_LOANS_COUNT
0,A002338349,Housing Loan,818517,115,640742,8627.0,142.0,0.0,0000000000000000000000000000000000000520520520...,Joint,2086000.0,681,0,36,0,0.0,52,SALARIED,Male,12.32,13.0,4.0,0.0,4.0,44.250000,1.0,1.0,2.0,0.0,14.0,2.0,0.0,0.0,1.0,1.0,0.0,13.0,1.0,0.0,0.0,97.0,0.0,524426.0,825000.0,129000.0,0.0,0.0,129000.0,381739.0,0.0,547026.0,1643517.0,0.0,0.0,0.0,298244.0,0.0,22600.0,640742.0,0.0,0.0,20
1,A002000537,Housing Loan,1243755,133,949446,500.0,156.0,0.0,0000000000000000000000000000000000000000000000...,Joint,1536000.0,784,0,36,0,0.0,39,SALARIED,Female,12.42,17.0,0.0,0.0,0.0,0.000000,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19000.0,0.0,0.0,19000.0,0.0,0.0,0.0,1243755.0,0.0,0.0,0.0,0.0,0.0,0.0,949446.0,0.0,0.0,3
2,A002421579,Housing Loan,1826422,81,1296849,16036.0,148.0,0.0,0000000000000000000000000000000000000000000000...,Joint,3587700.0,748,0,36,0,0.0,37,SALARIED,Male,10.87,17.0,0.0,0.0,0.0,0.000000,1.0,9.0,0.0,0.0,0.0,1.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3846792.0,0.0,0.0,4566792.0,0.0,0.0,0.0,1826422.0,415000.0,0.0,455004.0,0.0,0.0,0.0,1296849.0,414994.0,0.0,12
3,A002152345,Housing Loan,1847916,11,1724256,26996.0,174.0,0.0,0000000000000000000000000000000000000000000000...,Joint,3049600.0,786,0,12,0,0.0,54,SALARIED,Female,10.00,18.0,0.0,0.0,0.0,0.000000,0.0,5.0,1.0,1.0,5.0,3.0,0.0,0.0,3.0,1.0,1.0,5.0,1.0,0.0,0.0,150000.0,30000.0,520000.0,2424978.0,520000.0,0.0,0.0,1620000.0,150000.0,30000.0,520000.0,4287894.0,0.0,0.0,485042.0,0.0,0.0,0.0,1737702.0,0.0,0.0,15
4,A001952834,Housing Loan,2318386,110,1790937,25131.0,116.0,431551.0,5395705705405095065075075075075095095094794784...,Joint,2785400.0,664,0,36,0,0.0,49,SALARIED,Male,11.97,0.0,17.0,17.0,0.0,510.235294,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1919444.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4237830.0,0.0,0.0,0.0,0.0,0.0,0.0,1790937.0,0.0,0.0,5

In [18]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
df['new_feature'] = (df['HIGH_CREDIT_OR_SANCTIONED_AMOUNT']/(df['MONTH_OPENED']+1))
non_linear_corr = mutual_info_regression(df[['new_feature']], df['ACTUAL_ROI']).item()
linear_corr = df[['new_feature', 'ACTUAL_ROI']].corr().iloc[0, 1]
print(linear_corr)
print(non_linear_corr)

-0.10433889751349751
0.6999932279860577

In [21]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
df['new_feature'] = (df['COLLATERALVALUE']/(df['TU_SCORE']))
non_linear_corr = mutual_info_regression(df[['new_feature']], df['ACTUAL_ROI']).item()
linear_corr = df[['new_feature', 'ACTUAL_ROI']].corr().iloc[0, 1]
print(linear_corr)
print(non_linear_corr)

-0.18923350415365214
0.6385717019266455

In [22]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
df['new_feature'] = ((df['MONTH_PAYMENT_HISTORY_END'])*(df['REPAYMENT_TENURE']))
non_linear_corr = mutual_info_regression(df[['new_feature']], df['ACTUAL_ROI']).item()
linear_corr = df[['new_feature', 'ACTUAL_ROI']].corr().iloc[0, 1]
print(linear_corr)
print(non_linear_corr)

-0.4457237300877628
1.1719142212639104

In [ ]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
df['new_feature'] = ((df['ACTUAL_PAYMT_AMT'])*(df['REPAYMENT_TENURE']))
non_linear_corr = mutual_info_regression(df[['new_feature']], df['ACTUAL_ROI']).item()
linear_corr = df[['new_feature', 'ACTUAL_ROI']].corr().iloc[0, 1]
print(linear_corr)
print(non_linear_corr)

In [5]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
correlation_before = df[['HIGH_CREDIT_OR_SANCTIONED_AMOUNT', 'ACTUAL_ROI']].corr().iloc[0, 1]

mi_before_log_transform = mutual_info_regression(df[['HIGH_CREDIT_OR_SANCTIONED_AMOUNT']], df['ACTUAL_ROI']).item()

df['log_high_credit'] = np.log1p(df['HIGH_CREDIT_OR_SANCTIONED_AMOUNT'])

correlation_after = df[['log_high_credit', 'ACTUAL_ROI']].corr().iloc[0, 1]

mi_after_log_transform = mutual_info_regression(df[['log_high_credit']], df['ACTUAL_ROI']).item()
print(f'Correlation before logarithmic transformation: {correlation_before:.4f}')
print(f'Mutual Information before logarithmic transformation: {mi_before_log_transform:.4f}\n')

print(f'Correlation after logarithmic transformation: {correlation_after:.4f}')
print(f'Mutual Information after logarithmic transformation: {mi_after_log_transform:.4f}')

Correlation before logarithmic transformation: -0.1806
Mutual Information before logarithmic transformation: 0.8123

Correlation after logarithmic transformation: -0.7231
Mutual Information after logarithmic transformation: 0.7991

In [6]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression

# Assuming df is your DataFrame
# Replace df with your actual DataFrame if it's named differently

# Calculate correlation before transformation
correlation_before = df[['HIGH_CREDIT_OR_SANCTIONED_AMOUNT', 'ACTUAL_ROI']].corr().iloc[0, 1]

# Calculate mutual information before transformation
mi_before_sqrt_transform = mutual_info_regression(df[['HIGH_CREDIT_OR_SANCTIONED_AMOUNT']], df['ACTUAL_ROI']).item()

# Apply square root transformation to 'HIGH_CREDIT_OR_SANCTIONED_AMOUNT'
df['sqrt_high_credit'] = np.sqrt(df['HIGH_CREDIT_OR_SANCTIONED_AMOUNT'])

# Calculate correlation after transformation
correlation_after = df[['sqrt_high_credit', 'ACTUAL_ROI']].corr().iloc[0, 1]

# Calculate mutual information after transformation
mi_after_sqrt_transform = mutual_info_regression(df[['sqrt_high_credit']], df['ACTUAL_ROI']).item()

# Print the results
print(f'Correlation before square root transformation: {correlation_before:.4f}')
print(f'Mutual Information before square root transformation: {mi_before_sqrt_transform:.4f}\n')

print(f'Correlation after square root transformation: {correlation_after:.4f}')
print(f'Mutual Information after square root transformation: {mi_after_sqrt_transform:.4f}')

Correlation before square root transformation: -0.1806
Mutual Information before square root transformation: 0.8115

Correlation after square root transformation: -0.5550
Mutual Information after square root transformation: 0.7954

In [8]:
import numpy as np
from sklearn.feature_selection import mutual_info_regression
from scipy.stats import boxcox

# Assuming df is your DataFrame
# Replace df with your actual DataFrame if it's named differently

# Calculate correlation before transformation
correlation_before = df[['HIGH_CREDIT_OR_SANCTIONED_AMOUNT', 'ACTUAL_ROI']].corr().iloc[0, 1]
df['boxcox_high_credit'], lambda_value = boxcox(df['HIGH_CREDIT_OR_SANCTIONED_AMOUNT'] + 1)

# Calculate correlation after Box-Cox transformation
correlation_after_boxcox = df[['boxcox_high_credit', 'ACTUAL_ROI']].corr().iloc[0, 1]

# Calculate mutual information after Box-Cox transformation
mi_after_boxcox = mutual_info_regression(df[['boxcox_high_credit']], df['ACTUAL_ROI']).item()

# Print the results for Box-Cox transformation
print(f'\nCorrelation after Box-Cox transformation: {correlation_after_boxcox:.4f}')
print(f'Mutual Information after Box-Cox transformation: {mi_after_boxcox:.4f}')

Correlation after Box-Cox transformation: -0.6803
Mutual Information after Box-Cox transformation: 0.7950